# crontab -e
# Every hour/5'
# 5 */1 * * * /home/pi/v1/ptidej/cron/close_orders.sh >/dev/null 2>&1 
# At 6h5, 12h5, .., 22h5
# 5 6,12,14,16,18,19,20,21,22 * * * /home/pi/v1/ptidej/cron/close_orders.sh >/dev$

# Do not forget to change chmod +x on this .sh file

export DJANGO_SETTINGS_MODULE=mysite.$REPANIER.BE$_settings
export DJANGO_SETTINGS_MODULE_CELERY_APP=mysite
export DJANGO_SETTINGS_MODULE_CELERY_USER=$CEL_USER$
export DJANGO_SETTINGS_MODULE_CELERY_PASSWORD=$CEL_PASSWORD$
export DJANGO_SETTINGS_MODULE_DEBUG=False
export DJANGO_SETTINGS_MODULE_DATABASE_NAME=$NAME$
export DJANGO_SETTINGS_MODULE_DATABASE_USER=$USER$
export DJANGO_SETTINGS_MODULE_DATABASE_PASSWORD=$PASSWORD$
export =DJANGO_SETTINGS_MODULE_DATABASE_HOST=127.0.0.1
export =DJANGO_SETTINGS_MODULE_DATABASE_PORT=5432
export =DJANGO_SETTINGS_MODULE_EMAIL_HOST=$EMAIL_HOST$
export =DJANGO_SETTINGS_MODULE_EMAIL_HOST_USER=$EMAIL_HOST_USER$
export =DJANGO_SETTINGS_MODULE_EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD$
export =DJANGO_SETTINGS_MODULE_EMAIL_PORT=$EMAIL_PORT$
export =DJANGO_SETTINGS_MODULE_EMAIL_USE_TLS=True
export =DJANGO_SETTINGS_MODULE_ADMIN_NAME=$ADMIN_NAME$
export =DJANGO_SETTINGS_MODULE_ADMIN_EMAIL=$ADMIN_EMAIL$
/$PATH_TO$/$VIRTUAL_ENV$/python /$PATH_TO$/$VIRTUAL_ENV$/mysite/manage.py close_orders
