# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

PERMANENCE_DISABLED = '005'
PERMANENCE_PLANIFIED = '010' 
PERMANENCE_OPEN = '030'
PERMANENCE_CLOSED = '040'
PERMANENCE_SEND = '050'
PERMANENCE_PREPARED = '060'
PERMANENCE_DONE = '090'

LUT_PERMANENCE_STATUS = (
	(PERMANENCE_DISABLED, _('disabled')),
	(PERMANENCE_PLANIFIED, _('planified')),
	(PERMANENCE_OPEN, _('orders opened')),
	(PERMANENCE_CLOSED, _('orders closed')),
	(PERMANENCE_SEND, _('orders send to producers')),
	(PERMANENCE_PREPARED, _('orders prepared')),
	(PERMANENCE_DONE, _('done')),
)

PRODUCT_PLACEMENT_FREEZER = '010'
PRODUCT_PLACEMENT_FRIDGE = '020' 
PRODUCT_PLACEMENT_BASKET_BOTTOM = '030'
PRODUCT_PLACEMENT_BASKET_MIDDLE = '040'
PRODUCT_PLACEMENT_BASKET_TOP = '050'

LUT_PRODUCT_PLACEMENT = (
	(PRODUCT_PLACEMENT_FREEZER, _('freezer')),
	(PRODUCT_PLACEMENT_FRIDGE, _('fridge')),
	(PRODUCT_PLACEMENT_BASKET_BOTTOM, _('bottom of basket')),
	(PRODUCT_PLACEMENT_BASKET_MIDDLE, _('middle of basket')),
	(PRODUCT_PLACEMENT_BASKET_TOP, _('top of basket')),
)

SITE_ID_REPANIER = 1
SITE_ID_PRODUCER = 2
