import sys

from django.utils.translation import ugettext_lazy as _

DJANGO_IS_MIGRATION_RUNNING = "makemigrations" in sys.argv or "migrate" in sys.argv
REPANIER_SETTINGS_AFTER_AMOUNT = None
REPANIER_SETTINGS_BANK_ACCOUNT = None
REPANIER_SETTINGS_CONFIG = None
REPANIER_SETTINGS_CURRENCY_DISPLAY = None
REPANIER_SETTINGS_CURRENCY_XLSX = None
REPANIER_SETTINGS_DISPLAY_ANONYMOUS_ORDER_FORM = None
REPANIER_SETTINGS_DISPLAY_WHO_IS_WHO = None
REPANIER_SETTINGS_HOME_SITE = None
REPANIER_SETTINGS_MAX_WEEK_WO_PARTICIPATION = None
REPANIER_SETTINGS_MEMBERSHIP_FEE = None
REPANIER_SETTINGS_MEMBERSHIP_FEE_DURATION = None
REPANIER_SETTINGS_NOTIFICATION = None
REPANIER_SETTINGS_PAGE_BREAK_ON_CUSTOMER_CHECK = None
REPANIER_SETTINGS_SALES_NAME = _("Permanences")
REPANIER_SETTINGS_SALE_NAME = _("Permanence")
REPANIER_SETTINGS_SALE_ON_NAME = _("Permanence on ")
REPANIER_SETTINGS_SEND_ABSTRACT_ORDER_MAIL_TO_CUSTOMER = None
REPANIER_SETTINGS_SEND_INVOICE_MAIL_TO_CUSTOMER = None
REPANIER_SETTINGS_SEND_INVOICE_MAIL_TO_PRODUCER = None
REPANIER_SETTINGS_SEND_ORDER_MAIL_TO_BOARD = None
REPANIER_SETTINGS_VAT_ID = None
REPANIER_SETTINGS_XLSX_PORTRAIT = None
